const axios = require('axios');
const TelegramBot = require('node-telegram-bot-api');
const token = 'INSERISCI_IL_TUO_TOKEN_DEL_BOT';
const bot = new TelegramBot(token, { polling: true });

bot.onText(/\/help/, (msg) => {
  const chatId = msg.chat.id;
  const helpMessage = `
    Welcome! Here's what I can do:

    /joke - I'll tell you a joke generated by AI.
    /translate <language> <text> - I will translate the given text into the specified language (e.g., /translate en Ciao mondo).
    /help - Shows this help message.
  `;
  bot.sendMessage(chatId, helpMessage);
});

bot.onText(/\/joke/, async (msg) => {
  const chatId = msg.chat.id;

  try {
    const response = await axios.post('http://localhost:3001/gpt', {
      type: 'joke'
    });
    bot.sendMessage(chatId, response.data.message);
  } catch (error) {
    bot.sendMessage(chatId, 'Errore nel recupero della barzelletta.');
  }
});

bot.onText(/\/translate (\w+)\s+(.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const lang = match[1];
  const text = match[2];

  try {
    const response = await axios.post('http://localhost:3001/gpt', {
      type: 'translate',
      lang: lang,
      text: text
    });
    bot.sendMessage(chatId, response.data.message);
  } catch (error) {
    bot.sendMessage(chatId, 'Errore nella traduzione.');
  }
});

bot.on('message', (msg) => {
  const chatId = msg.chat.id;
  const text = msg.text.toLowerCase();

  if (text.includes("hello world")) {
    bot.sendMessage(chatId, "👋 Hello to you too!");
  }
});

async function fakeTranslate(text, lang) {
  return `[${lang}] ${text}`; 
}