require('dotenv').config();
const baseUrl = process.env.BASE_CHATGPT_URL
const token = process.env.TELEGRAM_API_TOKEN;

const axios = require('axios');
const TelegramBot = require('node-telegram-bot-api');
const bot = new TelegramBot(token, { polling: true });

bot.onText(/\/help/, (msg) => {
  const chatId = msg.chat.id;
  const helpMessage = `
    Welcome! Here's what I can do:

    /joke - I'll tell you a joke generated by AI.
    /translate <language> <text> - I will translate the given text into the specified language (e.g., /translate en Ciao mondo).
    /help - Shows this help message.
  `;
  bot.sendMessage(chatId, helpMessage);
});

bot.onText(/\/joke/, async (msg) => {
  const chatId = msg.chat.id;

  try {
    const response = await axios.get(`${baseUrl}/joke`);
    bot.sendMessage(chatId, response.data.joke);
  } catch (error) {
    console.log(error)
    bot.sendMessage(chatId, "Error in joke retrieval");
  }
});

bot.onText(/\/translate (\w+)\s+(.+)/, async (msg, match) => {
  const chatId = msg.chat.id;
  const lang = match[1];
  const text = match[2];

  try {
    const response = await axios.post(`${baseUrl}/translate/${lang}/`, { text });
    bot.sendMessage(chatId, response.data.translation);
  } catch (error) {
    bot.sendMessage(chatId, "Error in translation");
  }
});
